// Generated by CoffeeScript 1.6.3
(function() {
  var $doc, base_view, namespace;

  if (typeof window !== 'undefined') {
    namespace = window.review = {};
  } else {
    namespace = module.exports;
  }

  $doc = $(document);

  base_view = {};

  namespace.view = function(root, opts) {
    var delegate, generate_view;
    opts.__proto__ = base_view;
    generate_view = function(e, el) {
      var $root, view_instance;
      $root = $(el);
      if (!$root.is(root)) {
        $root = $root.parent(root);
      }
      view_instance = {
        $: $root,
        el: el,
        target: e.target
      };
      view_instance.__proto__ = opts;
      return view_instance;
    };
    delegate = function(specifier, handler) {
      var event_type, selectors, tokens;
      tokens = specifier.split(' ');
      event_type = tokens[0];
      selectors = [root].concat(tokens.slice(1)).join(' ');
      if ('string' === typeof handler) {
        handler = opts[handler];
      }
      return $doc.on(event_type, selectors, function(e) {
        var view_instance;
        view_instance = generate_view(e, this);
        return handler.call(view_instance, e);
      });
    };
    return $.each(opts.events, delegate);
  };

}).call(this);
